// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzuypioblawurwjachmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6dXlwaW9ibGF3dXJ3amFjaG1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0Mjk5OTgsImV4cCI6MjA2NTAwNTk5OH0.3kCTXUgwXQW56c56U8k_gftbgMfEwLtSoGma_zrny9E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);